######################
#PseudoPlayers Config#
######################

#DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 1


#########
#Formats#
#########

#Time format of first join if greater than difference specified below
#Use following codes:
#https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
FirstJoinTimeFormat: "MM-dd-yy h:mm:ss a"

#Difference between now and first join time that switches from a relative to absolute format
#In days
FirstJoinTimeDifference: 7

#Time format of last join/leave if greater than difference specified below
#Use following codes:
#https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
JoinLeaveTimeFormat: "MM-dd-yy h:mm:ss a"

#Difference between now and last join/leave time that switches from a relative to absolute format
#In days
JoinLeaveTimeDifference: 30