########################
# PseudoPlayers Config #
########################

# DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 4


###########
# Formats #
###########

# Difference between now and first join time that switches from a relative to absolute format (in days)
FirstJoinTimeDifference: 7

# Difference between now and last join/leave time that switches from a relative to absolute format (in days)
JoinLeaveTimeDifference: 30

# Teleportation Format
# {world} = world name
# {x} = x coordinate
# {y} = y coordinate
# {z} = z coordinate
TeleportationFormat: "tp @p {x} {y} {z}"


#########
# Other #
#########

# Aggressively take over /p command
AggressiveCommands: false