name: ${project.artifactId}
author: PseudoResonance
main: io.github.pseudoresonance.pseudoplayers.PseudoPlayers
version: ${revision}
description: Stores and gets data about players
api-version: 1.13
depend: [PseudoAPI]
softdepend: [Vault,VoxelSniper]
commands:
  pseudoplayers:
    description: PseudoPlayers Menu
  player:
    description: Shows player information
    aliases: [p,seen,lastseen,whois]
  ping:
    description: Shows player ping
    permission: pseudoplayers.ping
  nickname:
    description: Changes player nicknames
    permission: pseudoplayers.nickname
    aliases: [nick,name]
permissions:
  pseudoplayers.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoplayers.reset:
    description: Allows the player to reset the config
    default: op
    children:
      pseudoplayers.reload: true
  pseudoplayers.reloadlocalization:
    description: Allows the player to reload the localization
    default: op
  pseudoplayers.resetlocalization:
    description: Allows the player to reset the localization
    default: op
    children:
      pseudoplayers.reloadlocalization: true
  pseudoplayers.ping:
    description: Allows the player to view their ping
    default: true
  pseudoplayers.ping.others:
    description: Allows the player to view the ping of other players
    default: op
    children:
      pseudoplayers.ping: true
  pseudoplayers.nickname:
    description: Allows the player to use the nickname command
    default: op
  pseudoplayers.nickname.set:
    description: Allows the player to change their nickname
    default: op
    children:
      pseudoplayers.nickname: true
  pseudoplayers.nickname.set.others:
    description: Allows the player to change the nickname of other players
    default: op
    children:
      pseudoplayers.nickname.set: true
  pseudoplayers.nickname.view:
    description: Allows the player to view their nickname
    default: op
    children:
      pseudoplayers.nickname: true
  pseudoplayers.nickname.view.others:
    description: Allows the player to view other players' nicknames
    default: op
    children:
      pseudoplayers.nickname.view: true
  pseudoplayers.nickname.colors:
    description: Allows the player to use colors in their nickname
    default: op
    children:
      pseudoplayers.nickname: true
  pseudoplayers.nickname.formatting:
    description: Allows the player to use formatting in their nickname
    default: op
    children:
      pseudoplayers.nickname: true
  pseudoplayers.nickname.obfuscated:
    description: Allows the player to use obfuscation in their nickname
    default: op
    children:
      pseudoplayers.nickname: true
  pseudoplayers.nickname.special:
    description: Allows the player to use non ASCII characters in their nickname
    default: op
    children:
      pseudoplayers.nickname: true
  pseudoplayers.view:
    description: Allows the player to view player information about themselves
    default: true
  pseudoplayers.view.others:
    description: Allows the player to view player information about others
    default: true
    children:
      pseudoplayers.view: true
  pseudoplayers.view.uuid:
    description: Allows the player to see the uuid of a player
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.username:
    description: Allows the player to see the username of a nicknamed player
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.location:
    description: Allows the player to see where a player is
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.logoutlocation:
    description: Allows the player to see where a player last logged off
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.server:
    description: Allows the player to see what server a player is on
    default: true
    children:
      pseudoplayers.view: true
  pseudoplayers.view.lastserver:
    description: Allows the player to see what server a player was last on
    default: true
    children:
      pseudoplayers.view: true
  pseudoplayers.view.playtime:
    description: Allows the player to see how long a player has played
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.balance:
    description: Allows the player to see the balance of a player
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.ip:
    description: Allows the player to see the IP of a player
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.gamemode:
    description: Allows the player to see the gamemode of a player
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.health:
    description: Allows the player to see the health of a player
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.hunger:
    description: Allows the player to see the hunger of a player
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.op:
    description: Allows the player to see if a player is opped
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.god:
    description: Allows the player to see if a player is in god mode
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.view.fly:
    description: Allows the player to see if a player is in fly mode
    default: op
    children:
      pseudoplayers.view: true
  pseudoplayers.*:
    description: Gives the user all PseudoPlayers permissions
    default: op
    children:
      pseudoplayers.reset: true
      pseudoplayers.resetlocalization: true
      pseudoplayers.ping.others: true
      pseudoplayers.view.others: true
      pseudoplayers.view.uuid: true
      pseudoplayers.view.location: true
      pseudoplayers.view.logoutlocation: true
      pseudoplayers.view.server: true
      pseudoplayers.view.lastserver: true
      pseudoplayers.view.playtime: true
      pseudoplayers.view.balance: true
      pseudoplayers.view.ip: true
      pseudoplayers.view.gamemode: true
      pseudoplayers.view.health: true
      pseudoplayers.view.hunger: true
      pseudoplayers.view.op: true
      pseudoplayers.view.god: true
      pseudoplayers.view.fly: true
      pseudoplayers.nickname.set.others: true
      pseudoplayers.nickname.view.others: true
      pseudoplayers.nickname.colors: true
      pseudoplayers.nickname.formatting: true
      pseudoplayers.nickname.obfuscated: true
      pseudoplayers.nickname.special: true