name: PseudoPlayers
author: PseudoResonance
main: io.github.pseudoresonance.pseudoplayers.PseudoPlayers
version: 0.0.4
description: Stores and gets data about players
depend: [PseudoAPI]
softdepend: [VoxelSniper]
commands:
  pseudoplayers:
    description: PseudoPlayers Menu
  player:
    description: Shows player information
    aliases: [p,seen,lastseen,whois]
permissions:
  pseudoplayers.reset:
    description: Allows the player to reset the config
    default: op
  pseudoplayers.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoplayers.view:
    description: Allows the player to view player information about themselves
    default: true
  pseudoplayers.view.others:
    description: Allows the player to view player information about others
    default: true
    children:
      pseudoplayers.view: true
  pseudoplayers.view.logoutlocation:
    description: Allows the player to see where a player last logged off
    default: op
  pseudoplayers.*:
    description: Gives the user all PseudoPlayers permissions
    default: op
    children:
      pseudoplayers.reset: true
      pseudoplayers.reload: true
      pseudoplayers.view.others: true
      pseudoplayers.view.logoutlocation: true