name: WolfSpawners
author: WolfLeader116
main: io.github.wolfleader116.wolfspawners.bukkit.WolfSpawners
version: 1.0
description: Adds the ability to collect and change spawner types
depend: [WolfAPI]
commands:
  wolfspawners:
    description: WolfSpawners Menu
  spawner:
    description: Alias for WolfSpawners spawner
permissions:
  wolfspawners.reset:
    description: Allows the player to reset the config
    default: op
  wolfspawners.reload:
    description: Allows the player to reload the plugin
    default: op
  wolfspawners.collect:
    description: Allows the player to collect spawners
    default: true
  wolfspawners.collect.nosilk:
    description: Allows the player to collect spawners without silk touch
    default: op
    children:
      wolfspawners.collect: true
  wolfspawners.modify:
    description: Allows the player to change spawner types
    default: true
  wolfspawners.spawner:
    description: Allows the player to change spawner types without an egg
    default: op
    children:
      wolfspawners.modify: true
  wolfspawners.override:
    description: Allows the player to change override disallowed spawner types
    default: false
  wolfspawners.*:
    description: Gives the user all WolfSpawners permissions
    default: op
    children:
      wolfspawners.reset: true
      wolfspawners.reload: true
      wolfspawners.collect.nosilk: true
      wolfspawners.spawner: true
      wolfspawners.override: true